### ISSUE TITLE
Images schema

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_json_schema#2]
### What part of the schema is being reviewed?

![image](https://user-images.githubusercontent.com/112839/48261967-b9a8de00-e418-11e8-84d8-e42f67e6431a.png)

![image](https://user-images.githubusercontent.com/112839/48262006-de9d5100-e418-11e8-90e0-0b9db7c34ba9.png)

![image](https://user-images.githubusercontent.com/112839/48262062-0c829580-e419-11e8-8611-7a0cdfc547a4.png)

![image](https://user-images.githubusercontent.com/112839/48262082-21f7bf80-e419-11e8-840d-b46c846d8ad4.png)

Some cypher:

```cql
MATCH (primary:Class {short_form: 'FBbt_00007422' }) 
OPTIONAL MATCH (primary)<-[:SUBCLASSOF|INSTANCEOF*]-(i:Individual)<-[:depicts]-(:Individual)-[irw:in_register_with]->(template:Individual)-[:depicts]->(template_anat:Individual) 
WITH template, irw, i, primary limit 5 WITH COLLECT({ anatomy: { short_form: i.short_form, label: i.label, iri: i.iri, types: labels(i) } , image: { template: template.label, folder: irw.folder, index: coalesce(irw.index, 0) } }) AS images , primary
RETURN { core: { short_form: primary.short_form, label: primary.label, iri: primary.iri, types: labels(primary) } , description: primary.description, comment: coalesce(primary.`annotation-comment`, [])} as term ,images
```

### What is the intended usage/context of this part_of the schema?

Lists of images that are instances of some single class

The image subschema is also intended for use with single anatomical individuals with linked images.

e.g.  

![image](https://user-images.githubusercontent.com/112839/48262637-2fae4480-e41b-11e8-8874-9da2de7376f4.png)

For each we need a name, a path to a thumbnail and an internal link that opens the relevant anatomical individual in the correct template context.

Note - this should also be re-used for images shown in query results. 

The image subschema will be used for displaying single images of anatomical individuals

### Questions for reviewers 

If the answer to any question is no, please suggest improvements.

1. Are the names of properties intuitive and consistent?
1. Does the structure work to capture relationships between elements?
1. Is the internal documentation (description field content) sufficient?
1. Does this list of required fields make sense?
1. Is there any content missing?

**Comment by dosumis** [comment]
*Is there any content missing?*

1. Should displayed image reference dataset?  We used to do this (in a rather ugly way) back in VFB1
![image](https://user-images.githubusercontent.com/112839/48263112-ee1e9900-e41c-11e8-8ba3-6c2d7eeabea4.png)

2. @Robbie1977 Is the info sufficient to make links to the correct image files in all contexts?   Given that the aim of this schema is both to roll the site and serve as the download format for a user-facing API, is the info sufficient for users to obtain images?

**Comment by dosumis** [comment]
>  I also do not know what "index" is, but maybe that is so Gepetto specific that it does not need to be documented.

This is used for painted domains on a template -  which are typically defined by some index number  (numbering relative to some dataset of painted domains).    One possible issue with this:  I believe it is possible for a domain to have index number 0, but I've used this as the default value for when the query returns null for this field.  In this case, I think it may be better to simply omit the key when it is not present in the DB.    I may need help with Cypher to achieve this.

**Comment by dosumis** [comment]
From discussion with Nico:

1. We need to support 1 channel + many templates.  

=> split image into 2 keys:

```yaml

channel_images:  '...'
  channel: '...'
     core: '...'
     imaging_type: '...'

   images: '...'
       type: 'array'
       items: { $ref : #image }

image:
      template_anatomy: '...'
      template_channel: '...'
      folder: '...'
      index: '...'


  
```

**Comment by dosumis** [comment]
Update: this nesting is too hard to support directly from Cypher queries.  We need to flatten to a list of dicts:

```yaml
anatomy_images:
   - 
       anatomy: { "$ref": "#/definitions/minimal_entity_info" }
       channel: { core: { "$ref": "#/definitions/minimal_entity_info" }, imaging_technique: {"$ref": "#/definitions/minimal_entity_info"} }
       template: { image_template: { "$ref": "#/definitions/minimal_entity_info"} , anatomical_image: { "$ref": "#/definitions/minimal_entity_info"} }
       image_folder: { type: string }
       index: { type: int }
  - 
```
